version: ">= 0.15.0"

formatter: markdown

header-from: terraform.tf
footer-from: ""

sections:
  hide: []
  show: []
  

  hide-all: false
  show-all: true

content: |-
  {{ .Header }}
  This module deployes all resources needed for deploying Azure Virtual Desktop.

  ### NB!
  This module does not currently deploy Azuer Files Share and Files Directory for FSLogix due to a bug in the AzureRM Terraform Provider. This step has to be completed manually in scenarios where FSLogix is needed.

  ## Resources deployed by this module
  Which resources, and how many of each depends on your configuration
  - Resource Groups
  - AVD Workspaces
  - AVD Host Pools
  - AVD Application Groups
  - AVD Applications
  - Azure Shared Image Gallery
  - Azure Storage Account for FSLogix
  - Windows Virtual Machines as session hosts. Either joined to Azure AD or Azure Active Directory Domain Services joined. Will be registered to the specified Host Pool


  ## Resources NOT deployed by this module
  - Azure Virtual Network
  - Azure Subnet
  - Azure Network Security Groups
  - Azure AD Groupsh - Typically for designating AVD Users and Admins
  - Azure Key Vault - Typically for storage of secrets created by the module. Available in module outputs.
  - Azure Active Directory Domain Services

  {{ .Requirements }}

  ## Example

  ```hcl
  {{ include "examples/main.tf" }}
  ```

  {{ .Providers }}
  
  {{ .Modules }}

  {{ .Inputs }}
  
  {{ .Outputs }}
  
  {{ .Resources }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: false
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true
