name: Automation
on:
  pull_request:
    types: [ "opened" ]
  push:
    branches: [ "main" ]
    paths: [ "**.tf", "CHANGELOG.md"]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    name: Update README for changed modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@7a62208a0090636af2df1b739da46d27fd90bdc6 # v1.1.0
        with:
          working-dir: .
          git-push: "true"
          git-push-sign-off: "true"
          config-file: ".terraform-docs.yml"
          git-push-user-email: "41898282+github-actions[bot]@users.noreply.github.com"
          git-push-user-name: "github-actions[bot]"

  terraform:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]')
    name: Terraform checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Terraform
        run: terraform fmt -check -recursive

  release-please:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: terraform
    steps:
      - uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v4.1.0
        with:
          token: ${{ secrets.MARVIN_PAT }}
          release-type: terraform-module
          signoff: "Marvin <117985362+4t2-marvin@users.noreply.github.com>"
          #prerelease: true
